import Head from 'next/head';
import Link from 'next/link';

export default function Nav(){
  return (
    <div className='px-10 bg-gray-900'>
      <Head>
        <title>Brian Gee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="py-10 mb-12 flex justify-between">
        <Link href='/'>
          <h1  className="text-xl font-Iosevka text-white hover:text-blue-400 focus:shadow-outline focus:outline-none">Brian Gee</h1>
        </Link>
          <ul className="flex items-center">
            <li>
              <Link href='/'>
              <p className='bg-blue-500 hover:bg-blue-400 focus:shadow-outline focus:outline-none text-white px-4 py-2 rounded-md ml-5'>Home</p>
              </Link>
            </li>
            <li>
              <Link href='/portfolio'>
              <p className='bg-blue-500 hover:bg-blue-400 focus:shadow-outline focus:outline-none text-white px-4 py-2 rounded-md ml-5'>Portfolio</p>
              </Link>
            </li>
            <li>
              <Link href='/contact'>
              <p className='bg-blue-500 hover:bg-blue-400 focus:shadow-outline focus:outline-none text-white px-4 py-2 rounded-md ml-5'>Contact</p>
              </Link>
            </li>
            <li>
              <Link href='/resume'>
              <p className='bg-blue-500 hover:bg-blue-400 focus:shadow-outline focus:outline-none text-white px-4 py-2 rounded-md ml-5'>Resume</p>
              </Link>
            </li>
          </ul>
        </nav>
    </div>
  )
}