import Head from 'next/head';
import {BsFillMoonStarsFill, BsLinkedin, BsGithub} from 'react-icons/bs';
import Image from 'next/image';
import grim from '../public/grim_cropped.gif'
// import images from '../public/'
import { useState } from 'react';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Brian Gee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Nav bar */}
      <main className="bg-white px-10 dark:bg-black">
        <section className=" min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-Iosevka">Brian Gee</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl" />
              </li>
              <li>
                <a
                  className=" bg-gradient-to-r bg-cyan-400 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          {/* About Me */}
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-cyan-400">Brian Geertsma</h2>
            <h3 className="text-2xl py-2">Fullstack Developer</h3>
            <p className="text-medium py-5 leading-8 text-gray-800">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua.
              Viverra adipiscing at in tellus integer feugiat. Neque vitae
              tempus quam pellentesque. Odio pellentesque diam volutpat commodo
              sed egestas.
            </p>
          </div>

          <div className="relative mx-auto w-80 h-80 mt-20">
            <Image src={grim} />
          </div>
        </section>

        {/* Portfolio */}

        <section>
          <div className="text-center">
            <h3 className="text-3xl py-1">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 max-w-xl mx-auto">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua.
              Viverra adipiscing at in tellus integer feugiat. Neque vitae
              tempus quam pellentesque. Odio pellentesque diam volutpat commodo
              sed egestas.
            </p>
          </div>
          <div className="flex flex-col justify-center lg:flex-row lg:flex-wrap">
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <div className='basis-1/3 flex-1'>
                {/* <Image className='rounded-lg object- cover' width={'100%'}/> */}
                <h1>Testing</h1>
              </div>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <div className='basis-1/3 flex-1'>
                {/* <Image /> */}
                <h1>Testing</h1>
              </div>
            </div>
          </div>
        </section>

        {/* Footer */}
        <footer className="pt-20">
          <div className="text-5xl flex justify-center py-3 text-gray-600 space-x-10">
            <a href="https://www.linkedin.com/in/brian-geertsma-983052240/"><BsLinkedin /></a>
            <a href="https://github.com/brian-gee"><BsGithub  /></a>
          </div>
        </footer>
      </main>
    </div>
  );
}
