import Head from 'next/head';
import {BsFillMoonStarsFill, BsLinkedin, BsGithub} from 'react-icons/bs';
import Image from 'next/image';
import grim from '../public/grim_cropped.gif'
// import images from '../public/'
import { useState } from 'react';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Brian Gee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 dark:bg-black">
        <section className=" min-h-screen">

          {/* About Me */}
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-cyan-400">Brian Geertsma</h2>
            <h3 className="text-2xl py-2">Fullstack Developer</h3>
            <p className="text-medium py-5 leading-8 text-gray-800">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua.
              Viverra adipiscing at in tellus integer feugiat. Neque vitae
              tempus quam pellentesque. Odio pellentesque diam volutpat commodo
              sed egestas.
            </p>
          </div>

          <div className="relative mx-auto w-80 h-80 mt-20">
            <Image src={grim} />
          </div>
        </section>

        {/* Portfolio */}

        <section>
          <div className="text-center">
            <h3 className="text-3xl py-1">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 max-w-xl mx-auto">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua.
              Viverra adipiscing at in tellus integer feugiat. Neque vitae
              tempus quam pellentesque. Odio pellentesque diam volutpat commodo
              sed egestas.
            </p>
          </div>
          <div className="flex flex-col justify-center lg:flex-row lg:flex-wrap">
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <div className='basis-1/3 flex-1'>
                {/* <Image className='rounded-lg object- cover' width={'100%'}/> */}
                <h1>Testing</h1>
              </div>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <div className='basis-1/3 flex-1'>
                {/* <Image /> */}
                <h1>Testing</h1>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
