import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import workday from '../public/workday.png'
import jate from '../public/jate.png'
import noteTaker from '../public/note-taker.png'

export default function Portfolio() {
  return (
    <div>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Portfolio */}
      <main className="bg-white px-10 min-h-screen">
        <section>
          <div className="text-center">
            <h3 className="text-3xl py-1">Portfolio</h3>
          </div>
          {/* Work Day Scheduler Card */}
          <div className="flex flex-col justify-center lg:flex-row lg:flex-wrap">
              <div class="max-w-sm bg-white rounded-lg border border-gray-200 shadow-md">
                <a href="#">
                  <Image src={workday} alt='work day scheduler'/>
                </a>
                <div class="p-5">
                  <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900">Work Day Scheduler</h5>
                </div>
            </div>
            {/* JATE Card */}
            <div className="text-center shadow-lg p-10 rounded-xl m-5">
              <div className='basis-1/3 flex-1'>
                <h1 className='text-xl mb-5'>JATE</h1>
                <Link href='https://github.com/brian-gee/pwa-text-editor'>
                  <Image src={jate} alt='pwa text editor' className='rounded-lg object- cover' width={200} height={200} />
                </Link>
              </div>
            </div>
            {/* Note Taker Card */}
            <div className="text-center shadow-lg p-10 rounded-xl m-5">
              <div className='basis-1/3 flex-1'>
                <h1 className='text-xl mb-5'>Note Taker</h1>
                <Link href='https://github.com/brian-gee/'>
                  <Image src={noteTaker} alt='note taker' className='rounded-lg object- cover' width={200} height={200} />
                </Link>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
